name: Build Chrome Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create extension package
      run: |
        # 必要なファイルのみをパッケージに含める
        mkdir -p dist
        cp manifest.json dist/
        cp background.js dist/
        cp popup.html dist/
        cp popup.js dist/
        cp popup.css dist/
        cp options.html dist/
        cp options.js dist/
        cp options.css dist/
        cp shared.js dist/
        cp -r icons dist/
        
        # zipファイルを作成
        cd dist
        zip -r ../jumpmark-dock-extension.zip .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: jumpmark-dock-extension
        path: jumpmark-dock-extension.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: jumpmark-dock-extension.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}